services:
  postgres:
    container_name: bagile-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: bagile
      POSTGRES_PASSWORD: bagile123
      POSTGRES_DB: bagile
    ports:
      - "5432:5432"
    volumes:
      - bagile-data:/var/lib/postgresql/data
      - ./db/migrations:/scripts

volumes:
  bagile-data:
