name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Bagile/Bagile.sln

      - name: Build
        run: dotnet build Bagile/Bagile.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Bagile/Bagile.sln --configuration Release --no-build

      # Publish API project
      - name: Publish API
        run: dotnet publish Bagile/Bagile.Api/Bagile.Api.csproj -c Release -o output-api

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: bagile-api
          path: output-api

      # Publish ETL project
      - name: Publish ETL
        run: dotnet publish Bagile/Bagile.EtlService/Bagile.EtlService.csproj -c Release -o output-etl

      - name: Upload ETL artifact
        uses: actions/upload-artifact@v4
        with:
          name: bagile-etl
          path: output-etl
