name: CI/CD - ETL Service

on:
  push:
    branches: [ main ]
    tags:
      - 'etl-v*'
    paths:
      - 'Bagile/Bagile.EtlService/**'
      - 'Bagile/Bagile.Infrastructure/**'
      - '.github/workflows/cicd-etl.yml'
  pull_request:
    paths:
      - 'Bagile/Bagile.EtlService/**'
      - 'Bagile/Bagile.Infrastructure/**'
      - '.github/workflows/cicd-etl.yml'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Bagile/Bagile.sln

      - name: Build
        run: dotnet build Bagile/Bagile.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Bagile/Bagile.sln --configuration Release --no-build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image (ETL)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Bagile/Bagile.EtlService/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bagile-etl:latest
            ghcr.io/${{ github.repository_owner }}/bagile-etl:${{ github.sha }}   

      # Remove below publish to Azure when ready to swith away from Azure 
      - name: Publish ETL Service
        run: dotnet publish Bagile/Bagile.EtlService/Bagile.EtlService.csproj -c Release -o output-etl

      - name: Upload ETL artifact
        uses: actions/upload-artifact@v4
        with:
          name: bagile-etl
          path: output-etl

  deploy-etl:
    needs: build-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/etl-v') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Download ETL artifact
        uses: actions/download-artifact@v4
        with:
          name: bagile-etl
          path: bagile-etl

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Zip artifact
        run: cd bagile-etl && zip -r ../etl.zip .

      - name: Deploy ETL to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: bagile-etl
          package: etl.zip

