name: Deploy ETL

on:
  workflow_dispatch:
  push:
    tags:
      - 'etl-v*'   # Deploy only on tags like etl-v1.0.0

jobs:
  deploy-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Download ETL artifact
        uses: actions/download-artifact@v4
        with:
          name: bagile-etl

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ETL to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: bagile-etl
          package: bagile-etl
