name: Deploy ETL

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Download ETL Release Asset
        run: |
          gh release download ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --pattern "bagile-etl.zip"

      - name: Unzip package
        run: unzip bagile-etl.zip -d bagile-etl

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ETL to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: bagile-etl
          package: bagile-etl
